on: [pull_request]

env:
  OUT_DIR: outdir2

jobs:
  docker_hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello by docker action
    steps:
      - name: hello world action step
        id: hello
        uses: takada-s/hello-world-docker-action@v1.2.0
        with:
          who-to-greet: "john doe"
          output-dir: $OUT_DIR
      - name: failing step
        id: fails
        run: /usr/bin/false
      - name: upload artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pr-artifacts
          path: $OUT_DIR
